#!/bin/sh

STAGED_REGO_FILES=$(git diff --cached --name-only | grep "\.rego$")
OPA=$(command -v opa)
PASS=true

if [[ "$STAGED_REGO_FILES" = "" ]]; then
  exit 0
fi
# Check for open-policy-agent binary
if  [[ !  -x "$OPA" ]]; then
  printf "\t\033[41mPlease install open-policy-agent\033[0m (https://github.com/open-policy-agent/opa)"
  exit 1
fi

$OPA test -vl ./policies
STATUS=$?
echo $STATUS

if [[ $STATUS == 1 ]]; then
  printf "\t\033[31mopa test\033[0m \033[0;30m\033[41mFAILURE!\033[0m\n"
  PASS=false
fi

if [[ $STATUS == 2 ]]; then
  printf "\t\033[31mopa test\033[0m \033[0;30m\033[41mFAILURE!\033[0m\n"
  PASS=false
else
  printf "\t\033[32mopatest\033[0m \033[0;30m\033[42mpass\033[0m\n"
fi

for FILE in $STAGED_REGO_FILES
  do
    # Run opa fmt on the staged file
    opa fmt $FILE
  done

if ! $PASS; then
  printf "\033[0;30m\033[41mCOMMIT FAILED\033[0m\n"
  exit 1
else
  printf "\033[0;30m\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit 0